src/Wixet/BlogBundle/Entity/BlogEntry.php
<?php

namespace Wixet\BlogBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Wixet\BlogBundle\Paginator\CommentableEntityInterface;


/**
 * BlogEntry
 *
 * @ORM\Table(name="blog_entry")
 * @ORM\Entity(repositoryClass="Wixet\BlogBundle\Repository\BlogEntryRepository")
 */
class BlogEntry implements CommentableEntityInterface
{
    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->translations = new ArrayCollection();
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    private $public;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $image;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @var Locale
     * @ORM\ManyToOne(targetEntity="Locale")
     */
    private $locale;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $title;

    /**
     * @ORM\ManyToMany(targetEntity="Tag")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="entry")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     */
    private $author;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function getBodyPreview() {
        if(strpos($this->body, '<div style="page-break-after: always"><span style="display:none">&nbsp;</span></div>')) {
            return strstr($this->body, '<div style="page-break-after: always"><span style="display:none">&nbsp;</span></div>', true);
        } else {
            return $this->body;
        }

    }
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @param mixed $tags
     */
    public function setTags($tags)
    {
        $this->tags = $tags;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @param string $body
     */
    public function setBody($body)
    {
        $this->body = $body;
    }

    /**
     * @return Locale
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * @param Locale $locale
     */
    public function setLocale($locale)
    {
        $this->locale = $locale;
    }

    /**
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function __toString(){
        return $this->title;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * @return bool
     */
    public function isPublic()
    {
        return $this->public;
    }

    /**
     * @param bool $public
     */
    public function setPublic($public)
    {
        $this->public = $public;
    }

    private $numComments;
    public function setNumComments($num)
    {
        $this->numComments = $num;
    }

    public function getNumComments()
    {
        return $this->numComments;
    }


}

src/Wixet/BlogBundle/Controller/DefaultController.php
<?php

namespace Wixet\BlogBundle\Controller;

use Doctrine\ORM\Query;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Wixet\BlogBundle\Entity\Category;
use Wixet\BlogBundle\Service\BlogEntryService;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Wixet\BlogBundle\Entity\BlogEntry;
use Wixet\BlogBundle\Entity\CommentThread;
use Wixet\BlogBundle\Entity\Tag;
use Wixet\BlogBundle\Repository\BlogEntryRepository;


class DefaultController extends Controller
{
    /**
     * @Route("/tag/{slug}")
     * @Template
     * @ParamConverter("tag", options={"mapping": {"slug": "slug"}})
     * 
     * @param Tag $tag
     * @param Request $request
     * @return array
     */
    public function tagListAction(Tag $tag, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        /**
         * @var $repo BlogEntryRepository
         */
        $repo = $em->getRepository("WixetBlogBundle:BlogEntry");

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $repo->findMostRecentQuery($request->getLocale(), null, $tag),
            $request->get("page", 1),
            $request->get("size", 10),
            array("comment_info" => true)
        );

        return array("blogEntryPagination" => $pagination, "tag" => $tag);
    }

    /**
     * @Route("/{slug}")
     * @Template
     * @ParamConverter("category", options={"mapping": {"slug": "slug"}})
     *
     * @param Category $category
     * @param Request $request
     * @return array
     */
    public function categoryListAction(Category $category, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        /**
         * @var $repo BlogEntryRepository
         */
        $repo = $em->getRepository("WixetBlogBundle:BlogEntry");

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $repo->findMostRecentQuery($request->getLocale(), $category),
            $request->get("page", 1),
            $request->get("size", 10),
            array("comment_info" => true)
        );

        return array("blogEntryPagination" => $pagination, "category" => $category);
    }

    /**
     * @Route("/")
     * @Template
     *
     * @param Request $request
     * @return array
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        /**
         * @var $repo BlogEntryRepository
         */
        $repo = $em->getRepository("WixetBlogBundle:BlogEntry");

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $repo->findMostRecentQuery($request->getLocale()),
            $request->get("page", 1),
            $request->get("size", 10),
            array("comment_info" => true)
        );

        return array("blogEntryPagination" => $pagination);
    }
}

src/Wixet/BlogBundle/Resources/views/Default/blogEntryList.html.twig
<div class="blog-area">
    <div class="row">
        <div class="col-sm-8">
            <div class="blog-area-left">
                {% for entry in blogEntryPagination.items %}
                    <div class="single-blog">
                        <div class="single-blog-img">
                            <a href="{{ path('wixet_blog_entry_entry', {'category': entry.category.slug, 'slug': entry.slug }) }}"><img src="{{ entry.image | imagine_filter('blog_entry_title') }}" alt="{{ entry.title }}"></a>
                        </div>
                        <div class="single-blog-details">
                            <h4>{{ entry.createdAt | ldate }}</h4>
                            <h3>{{ entry.title }}</h3>
                            <div class="coments-info">
                                {% set count = entry.numComments %}
                                <p><span><i class="fa fa-user" aria-hidden="true"></i>{% trans %}por{% endtrans %} {{ entry.author.name }}</span><span><i class="fa fa-comments" aria-hidden="true"></i>{% transchoice count with {'%count%': count} from "FOSCommentBundle" %}fos_comment_thread_comment_count{% endtranschoice %}</span>{% if entry.category.name %}<span><i class="fa {{ entry.category.icon }}" aria-hidden="true"></i><a href="{{ path("wixet_blog_default_categorylist", {'slug': entry.category.slug}) }}">{{ entry.category.name }}</a></span>{% endif %} </p>
                            </div>
                            <p>{{ entry.bodyPreview | raw }}</p>
                            <a href="{{ path('wixet_blog_entry_entry', {'category': entry.category.slug, 'slug': entry.slug }) }}" class="blog-btn">{% trans %}Leer más{% endtrans %}</a>
                        </div>
                    </div>
                {% endfor %}
                {{ knp_pagination_render(blogEntryPagination) }}



            </div>
        </div>
        <div class="col-sm-4">
            <div class="blog-area-right">
                <!-- <div class="search-area widget_search" id="search">
                    <form method="get" id="searchform" action="http://blu.elated-themes.com/">
                        <div class="search-input">
                            <input value="" placeholder="Type your keyword" name="search" id="s" type="text">
                            <button type="submit" id="searchsubmit">
                                <span class="search-icon"><i class="fa fa-search"></i></span>
                            </button>
                        </div>
                    </form>
                </div>-->
                {{ sonata_block_render({ 'type': 'wixet.block.service.categories' }) }}

                {{ sonata_block_render({ 'type': 'wixet.block.service.tags' }) }}
            </div>
        </div>
    </div>
</div>

src/Wixet/BlogBundle/Resources/views/Default/categoryList.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% trans with {'%category%': category.name} %}Entradas sobre %category%{% endtrans %}{% endblock %}
{% block body %}

    <div class="row">
        <div class="col-md-12">
            <br>
            <h1>{% trans with {'%category%': category.name} %}Entradas sobre %category%{% endtrans %}</h1>
        </div>
    </div>
    {% include 'WixetBlogBundle:Default:blogEntryList.html.twig' %}

{% endblock %}

src/Wixet/BlogBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

            <div class="row">
                <div class="col-md-12">
                            <br>
                </div>
            </div>
            <div class="blog-area">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="blog-area-left">
                            {% for entry in blogEntryPagination.items %}
                                <div class="single-blog">
                                    <div class="single-blog-img">
                                        <a href="{{ url('wixet_blog_entry_entry', {'category': entry.category.name, 'slug': entry.slug }) }}"><img src="{{ entry.image }}" alt="{{ entry.title }}"></a>
                                    </div>
                                    <div class="single-blog-details">
                                        <h4>{{ entry.createdAt | ldate }}</h4>
                                        <h3>{{ entry.title }}</h3>
                                        <div class="coments-info">
                                            {% set count = entry.numComments %}
                                            <p><span><i class="fa fa-user" aria-hidden="true"></i>by {{ entry.author.name }}</span><span><i class="fa fa-comments" aria-hidden="true"></i>{% transchoice count with {'%count%': count} from "FOSCommentBundle" %}fos_comment_thread_comment_count{% endtranschoice %}</span>{% if entry.category.name %}<span><i class="fa {{ entry.category.icon }}" aria-hidden="true"></i>{{ entry.category.name }}</span>{% endif %} </p>
                                        </div>
                                        <p>{{ entry.bodyPreview | raw }}</p>
                                        <a href="{{ url('wixet_blog_entry_entry', {'category': entry.category.name, 'slug': entry.slug }) }}" class="blog-btn">Read More</a>
                                    </div>
                                </div>
                            {% endfor %}
                            {{ knp_pagination_render(blogEntryPagination) }}



                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="blog-area-right">
                            <div class="search-area widget_search" id="search">
                                <!-- blog-area-right search-area  Start  -->
                                <form method="get" id="searchform" action="http://blu.elated-themes.com/">
                                    <div class="search-input">
                                        <input value="" placeholder="Type your keyword" name="search" id="s" type="text">
                                        <button type="submit" id="searchsubmit">
                                            <span class="search-icon"><i class="fa fa-search"></i></span>
                                        </button>
                                    </div>
                                </form>
                            </div>
                            {{ sonata_block_render({ 'type': 'wixet.block.service.categories' }) }}

                            {{ sonata_block_render({ 'type': 'wixet.block.service.tags' }) }}
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

src/Wixet/BlogBundle/Resources/views/Default/tagList.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% trans with {'%tag%': tag.name} %}Entradas relacionadas con %tag%{% endtrans %}{% endblock %}
{% block body %}

    <div class="row">
        <div class="col-md-12">
            <br>
            <h1>Entradas relacionadas con {{ tag.name }}</h1>
        </div>
    </div>
    {% include 'WixetBlogBundle:Default:blogEntryList.html.twig' %}
{% endblock %}